### PR TITLE
require counts

### PR DESCRIPTION
**Pull request by nmercadeb**

### CODE REVIEW

**Comment by edward-burn** [comment]
fantastic, thanks @nmercadeb! I am wondering about the requirementType argument. One alternative way of doing it would be to have it like ingredientRange https://darwin-eu.github.io/CodelistGenerator/reference/getDrugIngredientCodes.html
```
- range = c(1,1) # exactly one record
- range = c(2,Inf) # two records or more
- range = c(1, 3) # between 1 and 3 records
```

If 
`- range = c(1, Inf)`
I would then get the same result as the flag function, right? 

We could even change from having negate to setting 
`- range = c(0, 0) # no records`


I don't have any stong feelings about which of these approaches will be most intuitive. What do you think?

**Comment by nmercadeb** [comment]
I like the idea!! It gives more flexibility than how I was doing it, and with less arguments!

Would you deprecate the flag then?

**Comment by edward-burn** [comment]
I would be tempted, because then it is fewer functions and arguments while retaining all the flexibility. But let's discuss with @catalamarti as I imagine he is likely to have opinions!

**Comment by edward-burn** [comment]
decided:
 just one function - requireCohortIntersect
 argument -intersections

**Comment by edward-burn** [comment]
superseeded by #220

**Pull request closed without merging**
